language: minimal

dist: xenial
sudo: required

env:
  - WIRESHARK_BRANCH=master-2.6 PLUGIN_DIR=$TRAVIS_BUILD_DIR

matrix:
  include:
    - name: Linux (gcc-8) standalone
      os: linux
      env:
        - CXX=g++-8
        - CC=gcc-8
        - BUILD_STANDALONE=yes
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages: g++-8
    - name: Linux (gcc-8)
      os: linux
      env:
        - CXX=g++-8
        - CC=gcc-8
        - BUILD_STANDALONE=no
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages: g++-8
    - name: Linux (clang) standalone
      os: linux
      env:
        - CXX=clang++
        - CC=clang
        - BUILD_STANDALONE=yes
    - name: Linux (clang)
      os: linux
      env:
        - CXX=clang++
        - CC=clang
        - BUILD_STANDALONE=no
    - name: OSX (xcode10.3 clang)
      os: osx
      osx_image: xcode10.3
      compiler: clang
      env:
        - BUILD_STANDALONE=no

before_install:
  - echo $TRAVIS_OS_NAME

  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
        ${PLUGIN_DIR}/tools/osx-provision-source.sh;
        PATH=/usr/local/opt/qt5/bin:$PATH;
    fi

  # See https://github.com/travis-ci/travis-ci/issues/5326
  - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")

  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ ${BUILD_STANDALONE} == "no" ]; then
        ${PLUGIN_DIR}/tools/ubuntu-provision-source.sh;
    fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ ${BUILD_STANDALONE} == "yes" ]; then
        ${PLUGIN_DIR}/tools/ubuntu-provision-standalone.sh;
    fi

install:
  - if [ ${BUILD_STANDALONE} == "no" ]; then
        ${PLUGIN_DIR}/tools/ubuntu-build-source.sh;
        export PATH=${PATH}:${HOME}/wireshark-${WIRESHARK_BRANCH}/build/run;
        export WIRESHARK_RUN_FROM_BUILD_DIRECTORY=1;
    fi
  - if [ ${BUILD_STANDALONE} == "yes" ]; then
        ${PLUGIN_DIR}/tools/ubuntu-build-standalone.sh;
    fi

script:
  - python ${PLUGIN_DIR}/tests/__init__.py

before_deploy:
  - if [ ${BUILD_STANDALONE} == "no" ]; then
        cp build/run/plugins/2.6/epan/sap.so build/sap-${TRAVIS_TAG}-${TRAVIS_OS_NAME}-x86-64.so;
    fi
  - if [ ${BUILD_STANDALONE} == "yes" ]; then
        mv build/sap.so build/sap-${TRAVIS_TAG}-${TRAVIS_OS_NAME}-x86-64.so;
    fi

deploy:
    provider: releases
    api_key:
        secure: "R+nmMCuHexC7Y7dZedEQ3mF2SE1kkfeazWHXtmWZFZF+v9wrtp+Er5SAKzvdf7NFpzj6ecF99f/Fpy6LLfdSmfQGzTiU9BRBodkx4ezEDEc0VVyS9V2I+UAYisenXfj7EtmX5N33tlj2ujogPt+RH0abrRmD1mxBqzzybPd7q6o="
    file: "build/*.so"
    file_glob: true
    skip_cleanup: true
    on:
        tags: true
        repo: SecureAuthCorp/SAP-Dissection-plug-in-for-Wireshark
        condition: "${BUILD_STANDALONE} == \"yes\" || ${TRAVIS_OS_NAME} == \"osx\""
